language: node_js
node_js:
- '7'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Gbx8jbRXgkzps0e370lbVbSa0OGFy1nLPerYh+2AWmf4ahsh6q00RIyKEX6WM00Fum46uZGOQ8vYcEBEoQkYvUXWuk+ATG1W8a2ylSE0oGALHnYANv8SLAb+jar5NOvpOeQ8qhYXkeiLrHHsHRV28ppEDwnJZhrF2fi70nwDbNVTMP9oPJTvDSG2xo9joS3HtR8pl6M+zd+6ivdEUndE/uWc8KKdORZDFiH2Gk7PxHYWKMlP9rC+ImsGFRmtZiYtFDUbqiPfYvUBN0VaMWmZ5F0hd4XayijwjwNHN+54waWShZSyQ84RAfUg/bZO52tOzYGgEyAI7o6J2Y9JVYbfPGuKuFWlPZEjr0YABHeXRIjot2lI8gptVzG5KMHnGzDbymVgABS85rCblf96c9yHpoqL9Wiftua+irr90gJdJ140Dd4p2rVJzmuZ0FQJIehrKXaK+XDFsaxksI6hb65Lca+VZdHzIdZ8LXo0PHZRfRvPnJNe7C8jX8MplTnee0pJV6g23wlJBsCONuD3Ub3iNGgJt7Z84kLyfxL5nFKslBf2cyhA1Z2kjLiWmlQnT202h0xcNdbIsh9nNW2zUbcqD1HM/lyYNwmu2dVcNNJdK7LR+hq5hFlI7IbNNa/TWF0AgXUBMy0tIWFAHbcFWeZrcmOOnQ0cMHfoNVW2o8Y6o28="
env:
  secure: "UuI5jnsC0+B+Bz3Z6lqNzJPUfie3XxH9FMi9e9hzT2ZZ61tkYUEtncSbaToo8tDt5UYaDyIsX2LIiIW0kCIX4xNWT/oPsfy2TnGNFSiGPuV1XcoTaZ5yXscKpkJi8+rwrGzW++iotY1T6sCmZOYwm3xdt/uwHknm0raY2aggLLcdKht3O9qWInOg3PLpDrzCWJpRX08IZqTo2LmP7Qp9ecF/dsihg2/Rip18XxU924SDIOgmnV3PogO9q4Uqqz7/xQSlDro/UgoqY6tDj8Qrq/ps9+bxaCVkzZd8sbgFsLiFH9leP5GPT2PzX54hhD3qLjL6q6iiFdpjWobFG7Gw5dt4HmGQsjE28hrbsAKtMFFO2ChXHkAiWjwk7CnUA6XpB3ZBxyr21ghewSZXXlHXmIdeebJlW+VkMsBjWyJEZXITh55C7C3LYpJFQgTH+ugn15YxVPdpeEDjYMOdGiTluLYL7VQzc8L3tuSqOigSae3UgjI7nvu/Pm//UIkOw0JUAlZGW/ZxU8FsWhdyri7miqWGzkONurB41YyIRSSKNl2mHklLrvEINPAIthaiFkiIq3NPx/RVCmkaoF7MZE40JyHwZhWR6SwP57M54UfBiBs7dp3ksNtfzLIDqAGWeVRMxyBHE59+/0Ymp5v0SWjCNaXyDZwL6XK0gZbaq1XeKzY="
