language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "0J5I9ZXn+vhUEoH7V+DHVeEZceAn1U0b73ijzKr+82wStrZhCJ9vCJ15emAhlHN2k3VU4XjP+MHdKJDwamTN4S382pJkjdh8rU8g/98zVyb1bBP75m/byuP+Z58sgI+xvW/30P2abzbcoZx60uR7Gf/FS45XFg9z6Fj5k0tEl6JzR5ysSSRE9CqHB2by2bZ+nRW03bhiGgEGimcDU5x6+aZFTv3l5/S4SiRHT8in5XZsD1IRlTu0VU/K1cLac2qatRWP0q+Dp3kOgCK/lqthVy13uF5bM7TVQAysbChNy7R4eCda7tBEiXjz0TuDsZt1LL6pxmRlgnEvyZVjOheX8JKb4vdyfWbIxTMhIed3nnbBjeS1TJxi/l/5pNXWseunQDvvuUX2q1hFYi2DQ/gb2abE0T6vFIzami0J9W6Q3q+u3DFTSqCLLapxvKrMtIMjn+lEzfGd1l6tL69E07wKFgbENiFxmbs2QEzuElpibXz6+MGD9yxoRoh+b3VABn6M/VrQiaRDBNpiVXbmU4V3CKuGUs/kEgMKeMR+cA1qTaXxtoaDD2vDUblli65OfKO7I4xNVMQFIvew+tKxSQ9o4A3IA9hFWgyNvEKeSHu2Gh/i5swaioO907KcXVHdZEXN5N6N8YmDWXxWUT/nBZC+M88sRTt9DU/zbljufhpbejM="
